export const ERROR_MESSAGES = {
    'User not found': 'Usuário não encontrado',
    'Error deleting user': 'Usuário não pode ser deletado, contém registros vinculados',
    'Email/Password incorrect': 'E-mail ou senha incorretos',
    'Company is not active': 'A empresa não está ativa',
    'User is not active': 'Usuário não está ativo',
    'A company with this CNPJ and email already exists': 'Empresa com este CNPJ e email já existe',
    'Descrição é obrigatório': 'Descrição é obrigatório',
    'File is empty': 'Envio do arquivo vazio',
    'Name is required': 'Nome é obrigatório',
    'Document type already exists': 'Número de documento já existe, favor verificar',
    'Email is required': 'Email é obrigatório',
    'User profile already exists': 'Perfil de usuário já existe',
    'Profile name is required': 'Nome do perfil é obrigatório',
    'User profile does not exists': 'Perfil de usuário não existe',
    'User group is being used': 'Grupo de usuário está sendo usado',
    'User profile is being used by a user': 'Perfil de usuário em uso no sistema',
    'Group name is required': 'Nome do grupo é obrigatório',
    'Group id is required': 'Id do grupo é obrigatório',
    'User group does not exists': 'Grupo de usuário não existe',
    'User group deleted successfully': 'Grupo de usuário deletado com sucesso',
    'User group already exists': 'Grupo de usuário já existe',
    'User with this email already exists': 'Usuário com este email já existe',
    'Document type not found': 'Modelo de documento não encontrado',
    'Description is required': 'Descrição é obrigatório',
    'Number document is required': 'Número do documento é obrigatório',
    'Type is required': 'Tipo é obrigatório',
    'User is required': 'Usuário é obrigatório',
    'Official Document already exists': 'Número de documento já existe, favor verificar',
    'Official document not found': 'Documento oficial não encontrado',
    'You are not authorized to read this official document': 'Você não está autorizado a ler este documento oficial',
    'Official document has been read': 'Documento oficial foi lido',
    'Official document already read': 'Documento oficial já foi lido',
    'Job name is required': 'Nome do cargo é obrigatório',
    'Company not found': 'Empresa não encontrada',
    'Job name already exists': 'Nome do cargo já existe, favor verificar',
    'Company id is required': 'Empresa é obrigatório',
    'Job name is being used': 'Nome do cargo está sendo usado',


}